### ISSUE TITLE
(com.aws.greengrass.Nucleus): local deployments attempt to download artifacts from receipe 

### ISSUE THREAD

**Issue by emaayan** [aws-greengrass/aws-greengrass-nucleus#1036]
when attempting to deploy a component from the command line that contains a recipe with artifacts from s3 the core attempts to download them from s3,  the documentation https://docs.aws.amazon.com/greengrass/v2/developerguide/component-recipe-reference.html#recipe-format
states:
When you develop a component with an archive artifact on a local core device, **you might not have a URI for that artifact. To test your component with an Unarchive option that extracts the artifact, specify a URI where the file name matches the name of your archive artifact file.** You can specify the URI where you expect to upload the archive artifact, or you can specify a new placeholder URI. For example, to extract the my_archive.zip artifact during a local deployment, you can specify s3://DOC-EXAMPLE-BUCKET/my_archive.zip.

the problem is that the core actually tries to download the artifacts and fails, which leads one to change the recipe file and comment out the artifacts section when doing local development 
this issue is also per https://forums.aws.amazon.com/thread.jspa?threadID=336887

**To Reproduce**
create a component with recipe that contains artifacts for example : 
```
RecipeFormatVersion: 2020-01-25
ComponentName: org.example.ggv2comp
ComponentVersion: '1.0.6'
ComponentDescription: Component for ggz
ComponentPublisher: Me
ComponentConfiguration:
  DefaultConfiguration:
    Message: world
    accessControl:
      aws.greengrass.ipc.mqttproxy: #https://docs.aws.amazon.com/greengrass/v2/developerguide/ipc-iot-core-mqtt.html#ipc-operation-subscribetoiotcore
        "org.example.ggv2comp.ggv2comp:pubsub:1":
          policyDescription: Allows access to publish to mqtt
          operations:
            - "aws.greengrass#PublishToIoTCore"
            - "aws.greengrass#SubscribeToIoTCore"
          resources:
            - "*"
Manifests:
  - Platform:
      os: linux
    Lifecycle:
      Run: |
        java -cp '{artifacts:path}/*' -jar {artifacts:path}/ggv2comp-1.0.6.jar
    Artifacts:
      - URI: 's3://ggv2artifacts/artifacts/org.example.ggv2comp.ggv2comp.zip'
        Unarchive: ZIP
```
deploy component with sudo /greengrass/v2/bin/greengrass-cli deployment create -r ./ -a ./artifacts -m "$1=$2"

**Expected behavior**
component deploys to the core 

**Actual behavior**
the core attempts to download the component 

**Environment**
 - OS: Ubuntu 20.04
 - JDK version: 8
 - Nucleus version: 2.3.0

**Additional context**
this blocks the ability to properly do a pipeline
