### ISSUE TITLE
(EasySetup): create a maven archtype for greengrass component 

### ISSUE THREAD

**Issue by emaayan** [aws-greengrass/aws-greengrass-nucleus#1052]
**Feature Description**
by using a maven archtype to create the skeleton project, (including the manfiest) it would be faster and easier to write components without falling into a lot of gotchas

**Use Case**
to onboard new developers who are not famliar with greengrass development 

**Proposed Solution**
the archtype will generate generate the following pom configuration 
a *filtered* recipe file inside the standard resources folder 
the recipe will include  the filters defined in properties in the pom, that would just be compose from the standard pom properties

```
<properties>
<ComponentName>${project.groupId}.${project.artifactId}</ComponentName>
<ComponentVersion>${project.version}</ComponentVersion>
<ComponentDescription>${project.description}</ComponentDescription>
<ComponentPublisher>publisher</ComponentPublisher>
<ComponentArtifact>${project.build.finalName}</ComponentArtifact>
<ComponentDir>${project.build.directory}/component/${ComponentName}/${ComponentVersion}</ComponentDir>
<s3-upload.bucket>pathtoupload</s3-upload.bucket>
</properties>
```

```
#https://docs.aws.amazon.com/greengrass/v2/developerguide/component-recipe-reference.html
RecipeFormatVersion: 2020-01-25
ComponentName: ${ComponentName} 
ComponentVersion: '${ComponentVersion}'
ComponentDescription: Component for gg
ComponentPublisher: ${ComponentPublisher}
ComponentConfiguration:
  DefaultConfiguration:
    Message: world  
Manifests:
  - Platform:
      os: linux
    Lifecycle:
      Run: |
        {artifacts:decompressedPath}/${ComponentArtifact}/run.sh
    Artifacts:
      - URI: 's3://${s3-upload.bucket}/artifacts/${ComponentArtifact}.zip'
        Unarchive: ZIP
        Permission:
          Execute: ALL
```

an assembly plugin that will have the following config

```
    <formats>
        <format>zip</format>
    </formats>

    <includeBaseDirectory>false</includeBaseDirectory>
    <dependencySets>
        <dependencySet>
        </dependencySet>
    </dependencySets>
    <fileSets>
        <fileSet>
            <includes>
                <include>${project.build.finalName}.jar</include>
            </includes>
<outputDirectory>.</outputDirectory>
        </fileSet>
        <fileSet>
            <directory>${project.build.scriptSourceDirectory}/</directory>
            <outputDirectory>.</outputDirectory>
            <filtered>true</filtered>
            <lineEnding>lf</lineEnding>
            <fileMode>0755</fileMode>
        </fileSet>
    </fileSets>
```

```
<plugin>
           <artifactId>maven-assembly-plugin</artifactId>
           <version>3.3.0</version><configuration>
            <attach>false</attach>
            <appendAssemblyId>false</appendAssemblyId>
            <finalName>${ComponentArtifact}</finalName>
             <outputDirectory>${project.build.directory}/component/${ComponentName}/${ComponentVersion}</outputDirectory>
                    <descriptors>
                        <descriptor>src/main/assembly.xml</descriptor>
                    </descriptors>

                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

```
and finally (and i didn't know how else to do it) a rename plugin to rename the receipe file automatically 
(you could always generate it once with the archtype but if you change any pom properties you'd have to change the file as well) 

```
  <plugin>
                <groupId>com.coderplus.maven.plugins</groupId>
                <artifactId>copy-rename-maven-plugin</artifactId>
                <version>1.0</version>
                <executions>
                    <execution>
                        <id>rename-descriptor-outputs</id>
                        <phase>install</phase>
                        <goals>
                            <goal>rename</goal>
                        </goals>
                        <configuration>
                            <sourceFile>${project.build.directory}/recipe.yaml</sourceFile>                            <destinationFile>${project.build.directory}/component/${ComponentName}-${ComponentVersion}.yaml</destinationFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

this would provide a good starting point especially if you include some shell scripts as example to local deply it
