### ISSUE TITLE
Ubuntu Core GG snap?

### ISSUE THREAD

**Issue by wills721** [aws-greengrass/aws-greengrass-nucleus#1689]
**Describe the bug**
Searching for Ubuntu Core Snap for Greengrass v2?

**To Reproduce**
[Steps to reproduce the behavior. If possible, provide a minimal amount of code that causes the bug.]
(https://snapcraft.io/aws-iot-greengrass)
Only v1 available and it is retired?

**Expected behavior**
Install greengrass v2 for Ubuntu Core using Snap (Ubuntu Core only supports Snap)

**Actual behavior**
Not available

**Environment**
 - OS: Ubuntu Core 24
 - JDK version:
 - Nucleus version:

**Additional context**

E.g. what is the impact of the bug?

**Comment by patrzhan** [comment]
Hi, we currently do not officially support snaps for Greengrass v2. Although it may be possible for us to consider it in the future, we don't currently have plans for it.

**Comment by patrzhan** [comment]
Thank you for your interest in Greengrass snap support. We will take this feedback and prioritize it internally - it's already in our backlog. If you are working with a Technical Account Manager, please make sure to also surface this feature request with them.

In the meantime, while we don't have an officially supported snap, we have had success getting Greengrass running on Ubuntu Core. Here's an example snapcraft.yaml that you can use as a reference. Note that version and source should be updated in the example.

snapcraft.yaml:
```
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: aws-iot-greengrass-v2
base: core20
# GGv2 version, such as 2.14.1
version: {VERSION}
summary: AWS supported software that extends cloud capabilities to local devices.
description: |
  AWS supported software that extends cloud capabilities to local devices.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

# declare home plug to allow access to files owned by the user in the user’s home ($HOME) directory
plugs:
  home-for-greengrass:
    interface: home
    read: all
  docker-cli:
    interface: docker
  docker-executables:
    content: docker-executables
    default-provider: docker
    interface: content
    target: $SNAP/docker-env
  root-dot-docker:
    interface: personal-files
    write:
    - $HOME/.docker

parts:
  greengrass:
    # See 'snapcraft plugins'
    plugin: dump
    # Add source link, in format https://d2s8p88vqu9w66.cloudfront.net/releases/greengrass-{VERSION}.zip
    source: {SOURCE}
    stage-packages:
      - openjdk-8-jre-headless
    build-packages:
      # We need to replace dangling symlink for java ssl certs.
      - ca-certificates-java
    override-build: |
      # execute default build step
      snapcraftctl build

      cd "$SNAPCRAFT_PART_INSTALL/usr/lib/jvm" || exit 2

      # The java-8-openjdk-<arch> dir has a different name for each arch, so
      # we need a symlink that references the actual name.
      # Described in: https://forum.snapcraft.io/t/advanced-grammar-for-layouts-or-workaround/17177/4

      # This will be a symlink to the arch-specific openjdk directory.
      OPENJDK_DIR_SYMLINK="java-8-openjdk-arch-symlink"

      case $(arch) in
              x86_64)
              OPENJDK_DIR="java-8-openjdk-amd64"
              ;;
      esac

      ln -s "$OPENJDK_DIR" "$OPENJDK_DIR_SYMLINK" || \
      (echo "failed to link $OPENJDK_DIR_SYMLINK -> $OPENJDK_DIR" \
      && exit 4)

      # The cacerts under /etc won't be accessible after build-time,
      # so the symlink leading to them will become a dangling symlinnk.
      # To avoid this, we'll copy them to the java subdirectory.
      cp /etc/ssl/certs/java/cacerts \
              "$SNAPCRAFT_PART_INSTALL/usr/lib/jvm/$OPENJDK_DIR_SYMLINK/jre/lib/security/cacerts" \
              || exit 5
      cp /etc/ssl/certs/java/cacerts \
              "$SNAPCRAFT_PART_INSTALL/etc/ssl/certs/java/cacerts" \
              || exit 6
  wrapper-scripts:
    plugin: dump
    source: local-scripts/

layout:
  # symlink java
  /usr/bin/java:
    symlink: $SNAP/usr/lib/jvm/java-8-openjdk-arch-symlink/jre/bin/java

apps:
  greengrass:
    command: exec-loader.sh
    daemon: simple
    install-mode: disable
    plugs:
      - mount-observe
      - network-bind
      - process-control
      - hardware-observe
      - log-observe
      - home-for-greengrass
      - docker-cli
      - docker-executables
      - root-dot-docker
```
configure hook:
```
#!/bin/bash

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

validate_greengrass_config() {
  greengrass_config="$(snapctl get greengrass-config)"

  # TODO: Add correct validation for config file
  if [ -z "$greengrass_config" ]; then
    echo "\"$greengrass_config\" is not a valid Greengrass config" >&2
    return 1
  fi
}
validate_greengrass_config
```
install hook:
```
#!/bin/bash

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Set default value for greengrass config.
# For now, it doesn't matter if this is invalid as user will provide config during setup
snapctl set greengrass-config="$HOME/defaultconfig.yaml"
```
We have this exec_loader.sh script referenced in the snapcraft.yaml:
```
#!/bin/sh

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# This script is necessary because loader script needs to be executed from
# $SNAP_DATA/greengrass/v2/alts/current/distro/bin path.
# Referencing this path from the snapcraft.yaml file results in path does not exist errors

set -o xtrace

GREENGRASS_CONFIG="$(snapctl get greengrass-config)"

# cd into install dir
cd "$SNAP_DATA" || exit 1
mkdir -p $SNAP_DATA/greengrass/v2 || exit 2
java -Droot=$SNAP_DATA/greengrass/v2 -Dlog.store=FILE -jar $SNAP/lib/Greengrass.jar \
     --start false --init-config $GREENGRASS_CONFIG --component-default-user root:root || exit 3


cd "$SNAP_DATA/greengrass/v2/alts/current/distro/bin" || exit 4
# TODO: Avoid running executables from write dir like $SNAP_DATA. Instead try running them from $SNAP
exec ./loader
```
Please let me know if you have any other questions!
