### ISSUE TITLE
Component recovery

### ISSUE THREAD

**Issue by tomikpik** [aws-greengrass/aws-greengrass-nucleus#1713]
Hi, can you please explain the component recovery mechanism? Nucleus 2.14.3

TLDR: The problem I'm facing is that I can't revert the component state back to RUNNING once it fails once. 

The [documentation](https://docs.aws.amazon.com/greengrass/v2/developerguide/component-recipe-reference.html#recover) for the recover step says:

> This step runs when a component enters the ERRORED state. If the component becomes ERRORED three times without successfully recovering, the component changes to the BROKEN state. To fix a BROKEN component, you must deploy it again.

What exactly does "successful recovery" mean? Is it exit code 0 of the `recover.Script` command or something else?

**Example recipe**
In my understanding, this component should always recover successfully, but the component becomes BROKEN when I kill the server three times.  
```
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentDescription: "Server and client"
Manifests:
  - Platform:
      architecture: amd64
      os: linux
    Artifacts:
      - Uri: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/server.amd64"
      - Uri: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/console.amd64"
    Lifecycle:
      install: "install.sh"
      run: "{artifacts:path}/server.amd64"
      recover: "echo 'recovering' && exit 0 "
```

Thank you
Tom
